markdown: rdiscount
permalink: /:title/
url: http://ittechbolg.github.io
name: ittechbolg
author: Kevin Yang
github: ittechbolg
pygments: true
safe: true
paginate: 20
about: "这里是 Kevin Yang 的个人博客，创建于 2015 年。
